services:
  db:
    image: mysql:8.0
    container_name: MYSQL_CONTAINER_FOR_PETISTAAN
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MY_SQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MY_SQL_DATABASE}
      MYSQL_USER: ${MY_SQL_USERNAME}
      MYSQL_PASSWORD: ${MY_SQL_PASSWORD}
    volumes:
      - ./mysql_data:/var/lib/mysql

  mailpit:
    image: axllent/mailpit:latest
    container_name: MAILPIT_CONTAINER_FOR_PETISTAAN
    ports:
      - "1025:1025" # SMTP server port
      - "8025:8025" # Web UI dashboard port
    restart: unless-stopped
